name: Build and Release Firmware

on:
  push:
    # branches:
    #     - main
    tags:
      - v*

jobs:
  nodemcu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install PlatformIO
        id: install-platformio
        run: python -m pip install platformio

      - name: Build Firmware for ESP8266
        id: build-firmware-esp8266
        run: platformio run -e esp8266

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
